version: '3.8'
services:
  kaggle-birdclef2023:
    build: ./Dockerfile
    container_name: kaggle-birdclef2023
    hostname: kaggle-birdclef2023
    shm_size: '28gb'
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: ["gpu"]
    volumes:
      - ./:/workspace:cached
      - ./kaggle:/kaggle:cached
    environment:
      TZ: Asia/Tokyo
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
      MLFLOW_TRACKING_URI: /workspace/log/mlruns/
    tty: true
