version: '3.8'
services:
  kaggle-birdclef2023:
    build: ./Dockerfile
    container_name: kaggle-birdclef2023
    hostname: kaggle-birdclef2023
    shm_size: '28gb'
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: ["gpu"]
    volumes:
      - /mnt/wslg:/mnt/wslg
      - /mnt/d/nakashimn/python/kaggle/BirdCLEF2023/:/workspace:cached
      - /mnt/d/nakashimn/python/kaggle/BirdCLEF2023/kaggle:/kaggle:cached
      - /mnt/c/Users/nakas/Data/birdclef-2023:/data_on_ssd:cached
    environment:
      TZ: Asia/Tokyo
      KAGGLE_USERNAME: ${KAGGLE_USERNAME}
      KAGGLE_KEY: ${KAGGLE_KEY}
      MLFLOW_TRACKING_URI: /workspace/log/mlruns/
      DISPLAY: host.docker.internal:0.0
    tty: true
